# Generated by Django 6.0.6 on 2026-07-26 02:49

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangoapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='subscriptionpayment',
            options={'ordering': ['-due_date']},
        ),
        migrations.AlterUniqueTogether(
            name='subscriptionpayment',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='subscriptionpayment',
            name='due_date',
            field=models.DateField(default=django.utils.timezone.now, help_text='The billing-cycle date this payment covers.'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='subscriptionpayment',
            name='is_paid',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='subscriptionpayment',
            name='paid_date',
            field=models.DateField(blank=True, help_text='Date the user marked this as paid.', null=True),
        ),
        migrations.AlterUniqueTogether(
            name='subscriptionpayment',
            unique_together={('subscription', 'due_date')},
        ),
    ]
